name: workspace publish
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary
          cache: true

      # Validação de versão
      - name: Validate version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          DENO_VERSION=$(deno eval "console.log(JSON.parse(Deno.readTextFileSync('deno.json')).version)")
          if [ "$TAG_VERSION" != "$DENO_VERSION" ]; then
            echo "❌ Version mismatch: tag v$TAG_VERSION != deno.json $DENO_VERSION"
            exit 1
          fi
          echo "✅ Versions match: $TAG_VERSION"

      - name: Format
        run: deno fmt --check

      - name: Test
        run: deno task test

      - name: Publish to JSR
        run: deno publish
